name: Build and Push Docker Image
on: 
  push: 
    branches: 
      - main
      - release/*
jobs:
  build-and-push: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker Image
        run: |
          docker buildx build \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/basic_website \
          . \
          --load
      
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic_website
